name: PR lint check

on:
  pull_request:
    types: [ opened, synchronize, edited ]
    branches:
      - master

jobs:
  build_and_test:
    name: Linting tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm run ci:build
      - name: Run linter
        run: npm run lint:all

